apiVersion: v1
kind: ConfigMap
metadata:
  name: laravel-config
data:
  DB_CONNECTION: mysql
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_DATABASE: test_deploy
  DB_USERNAME: laravel
  DB_PASSWORD: laravel

