apiVersion: v1
kind: ConfigMap
metadata:
  name: fmcore-configmap
data:
  spring.application.name: FMCore
  spring.datasource.url: jdbc:mysql://mysql-service:3306/fmcore?allowPublicKeyRetrieval=true
  spring.datasource.username: mysql
  spring.datasource.password: mysql
  spring.jpa.hibernate.ddl-auto: update
  spring.kafka.bootstrap-servers: kafka:29092
  spring.kafka.consumer.group-id: fmcore_2024
  spring.kafka.consumer.auto-offset-reset: earliest
  spring.kafka.producer.key-serializer: org.apache.kafka.common.serialization.StringSerializer
  spring.kafka.producer.value-serializer: org.apache.kafka.common.serialization.StringSerializer
  management.endpoints.web.exposure.include: "*"
  management.prometheus.metrics.export.enabled: "true"
